---
title: Heli-GPS Analysis in the Context of Mountain Pine Beetle
author: Leonard Buechner
date: '`r format(Sys.Date())`'
bibliography: references.bib 
biblio-style: apa
link-citations: true
# csl: apa.csl
output:
  md_document:
    variant: gfm
---


# Analysis of the Heli-GPS Data

## Introduction and Data
Most trees will have lost all needles, classifying as grey-attack, three years after they have been attacked by the Mountain Pine Beetle (MPB). When measuring LiDAR data at the end of March, al green-attack trees that have been attacked in 2019 and before, as well as all red-attack trees detected in 2020 and before, will now classify as grey attack. Of those treees that have been detected as re-attack in 2021, some will still classify as red-attack and others as grey-attack. This is due to the fact that the heli-GPS data provided by the government of Alberta cannot distinguish between different years of red-attack.

The roads are downloaded from several pages that I will have to cite here.
Flight locataions with the drone need to be accessable from the road for efficient data collection. As the drone has to stay in line of sight, it is not possible to fly far from the road.
Reachable areas will be defined through a buffer zone around paved and gravel roads as known from 
[@government_of_alberta_layer_nodate-1].

# References

<div id="refs"></div>